# Generated by Django 5.0.2 on 2024-02-18 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_selected',
        ),
        migrations.RemoveField(
            model_name='menuselection',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='menuselection',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuselection',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.booking'),
        ),
        migrations.AddField(
            model_name='menuselection',
            name='menus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu'),
        ),
        migrations.AlterField(
            model_name='menuselection',
            name='number_of_items',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
