# Generated by Django 5.0.2 on 2024-02-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_menu_menu_selected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuselection',
            old_name='bookings',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='menuselection',
            old_name='menus',
            new_name='menu',
        ),
    ]
