# Generated by Django 5.0.2 on 2024-02-09 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
