# Generated by Django 5.0.2 on 2024-03-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_bookings_menuselection_booking_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
        migrations.RenameField(
            model_name='menuselection',
            old_name='menu',
            new_name='menuitem',
        ),
    ]
