# Generated by Django 5.0.2 on 2024-04-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_menu_menuitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuselection',
            name='menuitem',
        ),
        migrations.AddField(
            model_name='menuselection',
            name='menuitem',
            field=models.ManyToManyField(blank=True, null=True, related_name='menuselections', to='restaurant.menuitem'),
        ),
    ]
