# Generated by Django 5.0.2 on 2024-04-07 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_menuselection_menuitem_menuselection_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='menuitems',
            field=models.ManyToManyField(blank=True, related_name='menuitems', through='restaurant.MenuSelection', to='restaurant.menuitem'),
        ),
        migrations.RemoveField(
            model_name='menuselection',
            name='menuitem',
        ),
        migrations.AddField(
            model_name='menuselection',
            name='menuitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem'),
        ),
    ]
